declare const _default: {
    xwho(): string;
    xwhen(): number;
    xwhat(xwhat: string): string;
    $lib(): string;
    $lib_version(): string;
    $platform(): string;
    $debug(): number;
    $is_login(): boolean;
    $session_id(): string;
    $screen_width(): number;
    $screen_height(): number;
    $language(): string;
    $user_agent(): string;
    $time_zone(): string;
    $startup_time(): string;
    $is_first_time(): boolean;
    $is_first_day(): boolean;
    $first_visit_time(): string;
    $first_visit_language(): any;
    $original_id(): string;
    $is_time_calibrated(): boolean;
    $referrer(): string;
    $referrer_domain(): string;
    $title(): string;
    $url(): string;
    $url_path(): string;
    $url_domain(): string;
    $utm_campaign_id(): string;
    $utm_source(): string;
    $utm_medium(): string;
    $utm_term(): string;
    $utm_content(): string;
    $utm_campaign(): string;
    $element_content(): string;
    $element_id(): string;
    $element_type(): string;
    $element_name(): string;
    $element_class_name(): string;
    $element_target_url(): string;
    $element_path(): string;
    $page_width(): number;
    $page_height(): number;
    $click_x(): number;
    $click_y(): number;
    $element_x(): number;
    $element_y(): number;
    $element_clickable(): number;
    $viewport_width(): number;
    $viewport_height(): number;
    $viewport_position(): number;
    $event_duration(): number;
    $device_type(): string;
    $web_crawler(): boolean;
};
/**
 * 获取属性值
 */
export default _default;
//# sourceMappingURL=getAttr.d.ts.map